#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : kazoo
Version  : 2.2.1
Release  : 19
URL      : https://pypi.python.org/packages/source/k/kazoo/kazoo-2.2.1.tar.gz
Source0  : https://pypi.python.org/packages/source/k/kazoo/kazoo-2.2.1.tar.gz
Summary  : Higher Level Zookeeper Client
Group    : Development/Tools
License  : Apache-2.0
Requires: kazoo-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : six

%description
=====
Kazoo
=====
.. image:: https://travis-ci.org/python-zk/kazoo.svg?branch=master
:target: https://travis-ci.org/python-zk/kazoo
:alt: Travis Build

%package python
Summary: python components for the kazoo package.
Group: Default

%description python
python components for the kazoo package.


%prep
%setup -q -n kazoo-2.2.1

%build
export LANG=C
export SOURCE_DATE_EPOCH=1484551131
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1484551131
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
