#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : kazoo
Version  : 2.5.0
Release  : 25
URL      : http://pypi.debian.net/kazoo/kazoo-2.5.0.tar.gz
Source0  : http://pypi.debian.net/kazoo/kazoo-2.5.0.tar.gz
Summary  : Higher Level Zookeeper Client
Group    : Development/Tools
License  : Apache-2.0
Requires: kazoo-python3
Requires: kazoo-license
Requires: kazoo-python
Requires: coverage
Requires: eventlet
Requires: flake8
Requires: gevent
Requires: nose
Requires: python-mock
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : eventlet
BuildRequires : gevent
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : six

%description
=====

%package license
Summary: license components for the kazoo package.
Group: Default

%description license
license components for the kazoo package.


%package python
Summary: python components for the kazoo package.
Group: Default
Requires: kazoo-python3

%description python
python components for the kazoo package.


%package python3
Summary: python3 components for the kazoo package.
Group: Default
Requires: python3-core

%description python3
python3 components for the kazoo package.


%prep
%setup -q -n kazoo-2.5.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1532211544
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/kazoo
cp LICENSE %{buildroot}/usr/share/doc/kazoo/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/kazoo/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
