#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : kazoo
Version  : 2.0
Release  : 7
URL      : https://pypi.python.org/packages/source/k/kazoo/kazoo-2.0.zip
Source0  : https://pypi.python.org/packages/source/k/kazoo/kazoo-2.0.zip
Summary  : Higher Level Zookeeper Client
Group    : Development/Tools
License  : Apache-2.0
Requires: kazoo-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
=====
Kazoo
=====
``kazoo`` implements a higher level API to `Apache Zookeeper`_ for Python
clients.

%package python
Summary: python components for the kazoo package.
Group: Default

%description python
python components for the kazoo package.


%prep
%setup -q -n kazoo-2.0

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python2 setup.py build -b py2 install --root=%{buildroot}
python3 setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
